### ISSUE TITLE
Listado de proyectos, portafolio de la comunidad.

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/website#126]
A muchos les parecerá suficiente el github, pero no es lo mismo presentar los proyectos en código fuente que con imágenes ilustrativas de lo que hace cada uno.

Fases:

- [x] La primera, tendrá los modelos y los html base sin estilizar, no se subirá content.lr para que no se pueda abrir la página de proyectos todavía, dado que está en construcción, se incluyen los html, por que sino, lektor arroja un error que no hay una plantilla para el modelo especificado
- [x] La segunda sera hacer los diseños respecto a como deberían verse las paginas del listado y los proyectos específicos
- [x] La tercera sera agregar los diferentes content.lr requeridos para los proyectos en español
- [ ] La cuarta será traducir los proyectos a ingles
- [x] La quinta integrar con github, puede hacerse en paralelo a la traducción
- [x] La sexta es que en los perfiles de los miembros aparezca a que proyectos han contribuido

**Comment by javierdaza** [comment]
¡¡¡ Bien pensado @Scot3004 !!!

**Comment by Scot3004** [comment]
https://www.getlektor.com/docs/guides/portfolio/

Propongo esa guiá como referencia para la implementación.

**Comment by javierdaza** [comment]
Se ve bien la propuesta. Le voy a trabajar al contenido primero

**Comment by javierdaza** [comment]
Puedes empezar listando estos proyectos. https://github.com/PyBAQ/hoja-de-ruta

**Comment by andresperezcera** [comment]
Necesitan ayuda con redacción y documentación?

**Comment by javierdaza** [comment]
Sobre la redacción y documentación pensaba que podríamos usar el texto de la [hoja de ruta](https://github.com/PyBAQ/hoja-de-ruta) aquí @andresperezcera 
Necesitamos ayuda  con la implementación en lektor

**Comment by andresperezcera** [comment]
Ok, yo puedo hacerlo tal como lo sugiere la guía con los respectivos textos y lo pongo como un pull request. Pero luego alguien debe maquillarlo, porque eso a mi me cuesta. Si no me creen vean mi [pagina](http://andresperezcera.xyz).

**Comment by javierdaza** [comment]
Perfecto @andresperezcera

**Comment by Scot3004** [comment]
@andresperezcera que avances tienes en esta tarea, te tengo una noticia, las rutas de esta pagina son:
- pybaq.co/proyectos
- pybaq.co/en/projects

**Comment by pyjavo** [comment]
Referencia visual para la sección de proyectos
https://frontend.cafe/cmyk

**Comment by pyjavo** [comment]
Acá estaré haciendo la actualización de la hoja de ruta https://github.com/PyBAQ/hoja-de-ruta/issues/2

**Comment by Scot3004** [comment]
Ya se actualizo la hoja de ruta
En cuanto a como agregar los proyectos se hará en varias fases
La primera, tendrá los modelos y los html base sin estilizar, no se subirá content.lr para que no se pueda abrir la página de proyectos todavía, dado que está en construcción, se incluyen los html, por que sino, lektor arroja un error que no hay una plantilla para el modelo especificado
La segunda sera hacer los diseños respecto a como deberían verse las paginas del listado y los proyectos específicos
La tercera sera agregar los diferentes content.lr requeridos para los proyectos en español
La cuarta será traducir los proyectos a ingles

**Comment by Scot3004** [comment]
Propuesta inicial 
<img width="1061" alt="image" src="https://github.com/PyBAQ/website/assets/1175402/69afb180-532f-412a-b243-a6e6ca2fd1c4">

**Comment by Scot3004** [comment]
Propuesta inicial

<img width="1060" alt="image" src="https://github.com/PyBAQ/website/assets/1175402/8f9c894a-e9d9-4f95-a437-e5a393e35d1a">

**Comment by Scot3004** [comment]
- Ya funciona el enlace entre proyectos y miembros, marque ese numeral como completado
- Creo que la integración con github, como la tenia pensada originalmente de traer los proyectos desde github y actualizar la lista, se complico un poco con la implementación que se hizo con checkboxes, toca investigar bien como hacerlo, asi que lo mas conveniente en este caso es crear un issue para ello
- Debemos relacionar las personas a los proyectos, y revisar si los miembros que se agregaron son los correctos
- Y pues ya para finalizar seria crear las traducciones a ingles de cada proyecto

**Comment by pyjavo** [comment]
Hasta este punto, ¿si hará falta hacer una integración con github? Igualmente en github ya aparecen quienes contribuyen y cuales son sus commits

**Comment by Scot3004** [comment]
No, además ya tenemos en los proyectos el GitHub del proyecto y en cada miembro su perfil en GitHub , lo marcare como completado
