### ISSUE TITLE
La página al cargar una pagina con imágenes, arroja un 404 para las imágenes tamaño 2x

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/website#279]
# Error en sitio web de python Barranquilla

## Comportamiento esperado

Al cargar la página no deberían aparecer errores de consola

## Comportamiento actual

![image](https://user-images.githubusercontent.com/1175402/113467235-68458300-9407-11eb-9988-cc01561c831b.png)

## Pasos para reproducir el error

1. Aparece en cualquiera de las páginas que tenga una imagen
2. Sucede al intentar descargar las imagenes en tamaño 2x
3. Es ocasionado por el script retina.js

**Comment by jorueda** [comment]
No he podido reproducir el error localmente o en el servidor. ¿Solamente ocurre con Mac?

![Captura de pantalla de 2021-04-06 15-37-26](https://user-images.githubusercontent.com/45174468/113775782-d1224900-96ee-11eb-9c4b-8c7d5cbafcb4.png)
![Captura de pantalla de 2021-04-06 15-39-03](https://user-images.githubusercontent.com/45174468/113775810-d7b0c080-96ee-11eb-8f1e-60cb03277a17.png)
![Captura de pantalla de 2021-04-06 15-41-44](https://user-images.githubusercontent.com/45174468/113775823-db444780-96ee-11eb-8715-f130aa857f40.png)
![Captura de pantalla de 2021-04-06 15-42-39](https://user-images.githubusercontent.com/45174468/113775831-dda6a180-96ee-11eb-853e-b10c7c41dcd2.png)

**Comment by Scot3004** [comment]
Con los cambios de plantilla retina.js se dejo de usar, sin embargo sigue por alli dando vueltas ese archivo, por ende el bug ya no se repite, pero si encontre que hay muchos assets haciendo bulto en el repositorio, asi que considero que deben ser eliminados
