### ISSUE TITLE
Cronjob para actualizar web con último evento

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/website#280]
# Solicitud de mejora en sitio web PyBAQ

Una tarea que de forma periódica actualice la web con el evento próximo

## Ventajas

No tenemos que estar pendientes de actualizarlo periódicamente.

## Desventajas

Ninguna por ahora

**Comment by pyjavo** [comment]
Una pregunta. Leí [en este articulo de Travis](https://blog.travis-ci.com/2021-02-22-switch) que están cambiando de OAuth a Github app. ¿Sabes si tenemos que cambiar algo en nuestra configuración @Scot3004 ?

**Comment by Scot3004** [comment]
Posiblemente, pero es relativamente sencillo de hacer

**Comment by Scot3004** [comment]
Me regalas la url del travis

**Comment by pyjavo** [comment]
@Scot3004 no hay. No me deja migrar ni añadir organizaciones

**Comment by pyjavo** [comment]
Este es el único repo que no me deja migrar

<img width="744" alt="sin_poder_migrar" src="https://user-images.githubusercontent.com/3085051/113781284-126a2700-96f6-11eb-99a3-9add4cd39208.png">

**Comment by pyjavo** [comment]
De alguna forma pude registrar la organización desde Chrome. Con el navegador Brave me estaba poniendo problemas

**Comment by Scot3004** [comment]
@pyjavo con github actions esto es super sencillo de implementar, de hecho el sr jorge dejo estas lineas para este proposito https://github.com/PyBAQ/website/blob/master/.github/workflows/deploy.yml#L12 (12 y 13) pero... si no se actualizan los eventos para que nos interesaria re compilar el sitio?

**Comment by pyjavo** [comment]
¡¡Buenísimo!!
Buena pregunta, los eventos solo se actualizan una vez al mes como mucho. Eso no quita el hecho de que siempre toca hacer un PR adicional para actualizar la página (esta vez coincidió que hicimos un cambio en la página y se actualizó el evento)

**Comment by Scot3004** [comment]
Para resolver este issue hay que crear un nuevo action
El cual se debe poder invocar con workflow_dispatch o bien cada vez que se quiera
Debe usar setup-python para instalar la versión de python que definamos
luego instalar requirements.txt del repositorio con pip
posteriormente ejecutar el script `scripts/events.py`
Finalmente deberia generar un pr con la salida del script, ver la siguiente documentación
https://cli.github.com/manual/gh_pr_create

para poder probar si se está ejecutando el action, aprendi que toca hacerlo entre ramas del propio fork, una vez se verifique que el action se ejecuto correctamente, enviar el link de la ejecución en el pull request, ya que hasta que no se haga el merge al master de pybaq, este no va a mostrar los checks

**Comment by jorueda** [comment]
Hola @pyjavo @Scot3004 me apunto a la tarea del cronjob 😄

**Comment by pyjavo** [comment]
@jorueda ¿cómo vamos con esto?¿necesitas ayuda?

**Comment by jorueda** [comment]
Hola, he estado un poco enredado, pero debo retomarlo e iniciar la investigación.

**Comment by jorueda** [comment]
> Para resolver este issue hay que crear un nuevo action El cual se debe poder invocar con `workflow_dispatch` ademas del `cron` Debe usar `setup-python` para instalar la versión de python que definamos luego instalar requirements.txt del repositorio con `pip` posteriormente ejecutar el script `scripts/events.py` Finalmente deberia generar un pr con la salida del script, ver la siguiente documentación https://cli.github.com/manual/gh_pr_create
> 
> para poder probar si se está ejecutando el action, aprendi que toca hacerlo entre ramas del propio fork, una vez se verifique que el action se ejecuto correctamente, enviar el link de la ejecución en el pull request, ya que hasta que no se haga el merge al master de pybaq, este no va a mostrar los checks

Hola @Scot3004 en la parte que dice usar `setup-python` existe la línea https://github.com/PyBAQ/website/blob/fc85142bc1198e2f38e547395cfacbfff3d70804/.github/workflows/deploy.yml#L31 y la parte de instalar requirements.txt está la línea https://github.com/PyBAQ/website/blob/fc85142bc1198e2f38e547395cfacbfff3d70804/.github/workflows/deploy.yml#L41 
entonces no habría que volver a colocar esas líneas cierto.
Por otro lado, lo que entiendo del último párrafo es que la acción llegaría hasta generar el pull request, esto es, no haría integración y deploy automático.

**Comment by Scot3004** [comment]
Si es un archivo yaml nuevo si habria que colocarlas, ya que cada job funciona por independiente, te puede ser util observar las diferencias entre los 2 yaml actuales (el de la construcción del sitio y el de las pruebas e2e)

**Comment by jorueda** [comment]
Hola, hice un pull request con el nuevo workflow para ejecutar semanalmente events.py y crear un nuevo pull request, desafortunamente no supe hacer como hacer para probarlo 100% simulando los cambios en meetup.json, hice pruebas parciales, si quizas fuera posible saber como hacer para simular el escenario completo.
