### ISSUE TITLE
Agregar Syntax Highlighting para publicaciones del blog.

### ISSUE THREAD

**Issue by andresperezcera** [PyBAQ/website#301]
# Solicitud de mejora en sitio web PyBAQ

La manera mas facil de implementar esto sería agregar highlight.js o prism.js a la plantilla del blog. Yo propongo prism.js.

## Ventajas

Mejora la lectura de codigo en posts del blog. Es critico para los posts que incluyen código.

## Desventajas

Sería un elemento mas para mantener actualizado.

**Comment by pyjavo** [comment]
¿Crees que tengas chance de ayudarnos con esto?

**Comment by andresperezcera** [comment]
Sip, mañana le trabajo temprano.

**Comment by javierdebug** [comment]
Oigan, estaba trabajando en esta Issue, pero no consigo implementar PrismJS con Lektor. PrismJS si funciona pero le tocaría al usuario agregar el HTML a los bloques código, es decir escribirlo así ej:
```
<pre class="line-numbers"><code class="language-python">
[Líneas de código]
</code></pre>
```
Lo cuál ya no sería plain Markdown.

Sin embargo encontré que Lektor tiene un plugin propio para syntax highlights (https://www.getlektor.com/plugins/lektor-markdown-highlighter/). Éste utiliza Pygmets y tiene varios temas por defecto, el cuento es que no funciona bien el fondo con Bootstrap (ver: https://stackoverflow.com/questions/34319981/pygments-bootstrap-highlight-shell-code-with-dark-background). Pero la solución es relativamente fácil ajustando el SCSS.

Así queda un bloque de código en una publicación en el Blog:

![image](https://user-images.githubusercontent.com/99869456/174403393-dd9d60e8-4fc0-42db-bf73-8e27229a6efa.png)

Nosé si les parece que arme un PR con estos cambios y así revisan o me dan alguna orientación sobre PrismJS con Lektor.

**Comment by andresperezcera** [comment]
Creo que sería mas facil con [hljs](https://highlightjs.org/), el siguiente codigo (reemplazo algunos caracteres para que se muestre como lo deseo):

```
'''js
var foo = 'bar';

function baz(s) {
   return foo + ':' + s;
}
'''
```


Se renderizaría de la siguiente manera que hljs puede transformar de la manera deseada.


```
<pre><code class="js language-js">var foo = 'bar';

function baz(s) {
   return foo + ':' + s;
}
</code></pre>
```
hljs es facil de implementar en paginas hechas con bootstrap. Aunque es mas simple.

**Comment by javierdebug** [comment]
> Creo que sería mas facil con [hljs](https://highlightjs.org/), el siguiente codigo (reemplazo algunos caracteres para que se muestre como lo deseo):
> 
> ```
> '''js
> var foo = 'bar';
> 
> function baz(s) {
>    return foo + ':' + s;
> }
> '''
> ```
> 
> Se renderizaría de la siguiente manera que hljs puede transformar de la manera deseada.
> 
> ```
> <pre><code class="js language-js">var foo = 'bar';
> 
> function baz(s) {
>    return foo + ':' + s;
> }
> </code></pre>
> ```
> 
> hljs es facil de implementar en paginas hechas con bootstrap. Aunque es mas simple.

Lo intenté con hljs pero pasa lo mismo (solo funciona al escribir el HTML no en Markdown). Al parecer es por la librería de Markdown que utiliza Lektor. En esta [issue](https://github.com/lektor/lektor/issues/23) del 2015 conversan sobre el tema; de ahí surgió el plugin que comenté antes.

Revisando el código fuente, la forma como renderiza Lektor los bloques de código es la siguiente:

El código: 
```
'''python
print("Hello World!")
'''
```
Lo transforma en:
`<div class="hll"><pre><span></span><span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Hello World!&quot;</span><span class="p">)</span></pre></div>`


No lo ubica entre los tags pre y code.

**Comment by andresperezcera** [comment]
Lo raro es que lo tengo funcionando con lektor. Pero ahora que veo yo no
uso Markdown sino Asciidoc. Voy a probar con Markdown y te dejo saber.
