### ISSUE TITLE
Agregar a fer a lista de organizadores como colaborador

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/website#306]
# Solicitud de mejora en sitio web PyBAQ

Agregar a fer a la página de nosotros

## Ventajas

Reflejar la realidad de el equipo

## Desventajas

Toca dedicarle su ratico

**Comment by pyjavo** [comment]
Gracias @Scot3004 
Los colaboradores se suelen agregar a la página luego de un "período de prueba". Esto porque mucha gente dice que si va a ayudar pero luego a la final no lo hacen jeje
Lo marcaré como wontfix por el momento

**Comment by Scot3004** [comment]
Para mi que el periodo de prueba finalizo y lo paso con honores 😆

**Comment by pyjavo** [comment]
Concuerdo. Hay que agregar a Fernando

**Comment by pyjavo** [comment]
Esta es la foto de Fernando Llinás
https://media-exp1.licdn.com/dms/image/C4E03AQHVk9jwF5-GXw/profile-displayphoto-shrink_400_400/0/1659544235067?e=1666828800&v=beta&t=Nl2mLcWUhOQVJwQCog9xzuJa6Ej-w0ljx_IlnuSUcHc
