### ISSUE TITLE
 Agregar logos de Python Colombia y Empanada Fund

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/website#315]
# Solicitud de mejora en sitio web PyBAQ

Agregar los logos, de empanada fund y python colombia. y enlazar a los sitios web de cada sponsor

Empanada fund
https://www.notion.so/The-Empanada-Fund-857632d4c05740ecb8a2c1e8f8f0b116

Python colombia
https://www.python.org.co/

Koombea
https://www.koombea.com/

Github
https://github.com/

Python software foundation
https://www.python.org/psf/

¿Deberiamos agregar netlify que es donde tenemos los preview deploy del sitio web?
Netlify

https://www.netlify.com/

## Ventajas

Enlaza nuestro sitio a nuestros patrocinadores

## Desventajas

Ninguna

**Comment by pyjavo** [comment]
Ahora que mencionas Netlify, no se si valga la pena incluirla en los patrocinadores (incluyendo a GitHub Pages). Al fin y al cabo son herramientas con una versión *gratuita*

¿Qué opinas si solo se deja Koombea, PSF, Python Colombia y Empanada Fund?

**Comment by Scot3004** [comment]
De acuerdo, por eso lo coloque con un gran signo de interrogación :D

**Comment by Scot3004** [comment]
Es correcto, el archivo es sponsor.json, en cuanto a las imagenes creo que no toca anteponerlo, ya que usualmente los navegadores son capaces de resolverlo, la razón por la que no aparecen es por que en estos momentos dichos recursos no están en master.

En cuanto a las descripciones en estos momentos ya no se usan, en alguna versión anterior se mostraba que hacia cada patrocinador
Python colombia: provee las heramientas online donde hacemos las transmisiones
Empanada fund: nos dio fondos para dar a conocer el sector tecnologia
Pa resumir la descripción puedes dejarla en blanco, pero considere pertinente decir que hace cada uno, por que en lo personal yo lo pondria, violando yagni jaja

**Comment by javierdebug** [comment]
Gracias @Scot3004, por la aclaración.

Sobre el logo de EmpanaFund solo encontré el que tienen en Twitter pero aparece con una relación de aspecto diferente a los otros logos, es cuadrado contrario a rectángulo. Escalé la imagen pero no se ve como los otros, ¿tienen el logo o saben donde conseguirlo?. Y otra cosa, ahora con 4 logos en lugar de 3 ese apartado se ve raro (ver imagen), ¿Que archivo define el número de columnas de ese apartado para editarlo y dejar una fila con 4 logos o dos filas con 2 imágenes cada una?

![image](https://user-images.githubusercontent.com/99869456/173636328-57a170e0-4020-4504-b1e8-54daa2e8beb0.png)

**Comment by pyjavo** [comment]
Pues el notion sigue teniendo ese [logo horizontal](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fe8535927-3ae6-4e5b-af2d-781c87e2a303%2F1_FiWiixAyXOcMXirl1c7zGg.png?table=block&id=857632d4-c057-40ec-b8a2-c1e8f8f0b116&spaceId=fcd22b34-3810-48c1-b705-3d1a76e1b800&width=2000&userId=5fafd6b5-76fb-4726-89c0-ecf312f3c4ac&cache=v2).  entonces por lo pronto no tenemos más (ya quedaría así).

**Comment by Scot3004** [comment]
Las columnas están definidas en el flowblock de sponsor https://github.com/PyBAQ/website/blob/master/templates/blocks/sponsors.html
