### ISSUE TITLE
Corregir las instrucciones del archivo README.md

### ISSUE THREAD

**Issue by javierdebug** [PyBAQ/website#336]
# Error en las instrucciones del archivo README.md sobre compilar CSS

## Comportamiento esperado

Al ejecutar el código 'npm build', se compila el CSS del sitio y se aprecian los cambios realizados.

## Comportamiento actual

El terminal muestra un error al ejecutar la línea de código

```
Unknown command: "build"

Did you mean this?
    npm run build # run the "build" package script

To see a list of supported npm commands, run:
  npm help
```

## Pasos para reproducir el error

1. Edita el estilo modificando un archivo SCSS.
2. Intenta compilar CSS con el código 'npm build'.

**Comment by Scot3004** [comment]
Efectivamente, el comando correcto en esta linea es `npm run build`, buen ojo!

![imagen](https://user-images.githubusercontent.com/1175402/182272842-bd195044-4a48-46f1-8ece-c9935b98043d.png)
