### ISSUE TITLE
Revisar cursos datacamp

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/website#353]
# Solicitud de mejora en sitio web PyBAQ

De datacamp nos escribieron para que revisaramos los cursos gratuitos que tienen.

I was browsing through your website and I saw that you provide some helpful free resources to your site visitors here: https://pybaq.co/en/blog/primeros-pasos-en-python/.

_I was hoping you might link one or more of our free resources._

_We have 6 courses that are completely free:_

- [Introduction to Python](https://www.datacamp.com/courses/intro-to-python-for-data-science)
- [Introduction to SQL](https://www.datacamp.com/courses/introduction-to-sql)
- [Introduction to R ](https://www.datacamp.com/courses/free-introduction-to-r)
- [Machine Learning for Everyone](https://www.datacamp.com/courses/machine-learning-for-everyone)
- [Data Science for Everyone](https://www.datacamp.com/courses/data-science-for-everyone)
- [Data Engineering for Everyone](https://www.datacamp.com/courses/data-engineering-for-everyone)

## Ventajas

Agregar más recursos gratuitos al artículo

## Desventajas

Requiere tiempo en revisar los cursos y agregar nuevas actualizaciones al artículo

**Comment by andresperezcera** [comment]
Ya inicié estos cursos, a primera vista se ven claramente enfocados en analisis de datos (lo que es consistente con su fortaleza). Seguiré avanzando hasta terminar el primer curso y basado en eso agregaré los links y posiblemente adicione un post acerca de Datacamp.

**Comment by andresperezcera** [comment]
Tras tomar los cursos básicos, me di cuenta que tienen poco o ningún contenido. La metodología es muy buena ya que no se trata solo de escribir sino de saber como escribir expresiones en Python, R o SQL. En Python particularmente vemos que solo cubren elementos basicos de operadores, variables, tipos de variables y conversión entre tipos; todo otro tema requiere pago. Esto, en mi opinion deja este curso por fuera del minimo aceptable. Lo que si se podría hacer es incluir una referencia a la lista de Libros y Tutoriales listados en la pagina PSF:
- https://wiki.python.org/moin/IntroductoryBooks
- https://wiki.python.org/moin/BeginnersGuide/Programmers
