### ISSUE TITLE
Traducir artículo scrapping con beautifulsoup

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/website#363]
# Solicitud de mejora en sitio web PyBAQ

Crear traduccion de articulo archivado https://web.archive.org/web/20220922122233/https://www.dataquest.io/blog/web-scraping-beautifulsoup/

## Ventajas

Documentación sobre la herramienta con un artículo chévere

## Desventajas

Toca revisarlo en way back machine porque lo borraron de la página oficial

**Comment by jdgc14** [comment]
Me gustaria hacer la traduccion del archivo para la web
