### ISSUE TITLE
El travis build ya no funciona

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/website#366]
# Error en sitio web de python Barranquilla

## Comportamiento esperado

Debería permitirnos hacer el build para construir los cambios recientes de la página web

## Comportamiento actual

Dice que debido a un balance negativo se han suspendido los builds
<img width="1272" alt="Captura de Pantalla 2023-02-08 a la(s) 9 20 57 p m" src="https://user-images.githubusercontent.com/3085051/217851049-e965b0a4-471d-49b8-96a7-6f526ae99572.png">

## Pasos para reproducir el error

1. aceptar cualquier PR
2. Ver que no se construye nada nuevo y la página no se actualiza

**Comment by pyjavo** [comment]
Parece que nos va a tocar mudarnos de Travis a otra alternativa que nos permita construir el sitio web "gratis" @Scot3004 @jorueda

**Comment by Scot3004** [comment]
No nos compliquemos, ya tenemos netlify, se le puede configurar los dns y sale pa pintura

**Comment by jorueda** [comment]
Me apunto a aprender del tema.

**Comment by pyjavo** [comment]
De acuerdo contigo Scot3004 y con el voto de @krthr . Sin embargo, esta vez me voy con jorueda por el tema de aprendizaje jeje 😅😅😅. 

A mi también me gustaría aprender a ver como se implementa el **build a github pages** usando recursos de Github (CI/CD con github actions) mientras que Netlify se mantendría igual a como se viene usando ¿Qué opinas @Scot3004 ?

**Comment by Scot3004** [comment]
Podria funcionar, aunque mantener 2 pipelines tiene su reto
