### ISSUE TITLE
Problema con el ancho de los perfiles

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/website#370]
Adjunto imágenes con diferentes "width"

<img width="1258" alt="Captura de Pantalla 2023-02-20 a la(s) 9 12 00 a m" src="https://user-images.githubusercontent.com/3085051/220131295-899d9651-c46f-47e6-befa-9a39a27b0b69.png">

<img width="1274" alt="Captura de Pantalla 2023-02-20 a la(s) 9 12 26 a m" src="https://user-images.githubusercontent.com/3085051/220131338-566193c1-f6f7-4031-b4e9-ef3ed4e2632c.png">

<img width="1268" alt="Captura de Pantalla 2023-02-20 a la(s) 9 12 55 a m" src="https://user-images.githubusercontent.com/3085051/220131429-c62baa0c-edcf-4c15-9502-3cd4d81e9306.png">

_Originally posted by @pyjavo in https://github.com/PyBAQ/website/issues/369#issuecomment-1437094516_

**Comment by Scot3004** [comment]
Para este issue vamos a crear un diseño en figma que nos diga cómo queremos ver esta página, si bien     ya hace lo que tiene que hacer, toca ponerla bonita
