### ISSUE TITLE
Ejecutar pruebas e2e en los Pull request

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/website#377]
# Solicitud de mejora en sitio web PyBAQ

Usar las pruebas e2e que están en la carpeta tests

## Ventajas

- Tendriamos tests automatizados antes de proceder con los merge
- Esa es una oportunidad de aprender como funciona un pipeline con pruebas  e2e
- Ya hicimos las pruebas, pero estan alli sin uso, se puede aprovechar eso que se hizo

## Desventajas

- Los build minutes se acabarian mas rapido, la sola ejecución de estas pruebas no bajaria de 20 segundos
- Entre mas pruebas se agreguen mas va a demorar el pipeline corriendo

**Comment by pyjavo** [comment]
¿Sabes de casualidad cuantos minutos gratis tenemos al mes para los build?

**Comment by Scot3004** [comment]
2000 build minutes https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

**Comment by pyjavo** [comment]
Gracias @Scot3004 

Para aprobar el PR #379 opino que sería bueno tener más contexto de por qué esto es necesario y qué ventajas aporta al proyecto. Sería bueno de disponer una reunión para compartir este nuevo feature con el equipo. 
Saludos :)
