### ISSUE TITLE
Onboarding en plataformas en la nube

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/website#384]
# Solicitud de mejora en sitio web PyBAQ

He visto quejas debido a que la configuración inicial del proyecto para una persona no tecnica es bastante tediosa, por ende esto va enfocado a resolver esta situación, estuve investigando alternativas de desarrollo en la nube (que no requieren configurar nada en nuestras maquinas) y encontre entre ellas [github codespaces](https://github.com/features/codespaces), [gitpod](https://www.gitpod.io/) y asi facilitar a personas no tan tecnicas el uso del lektor admin en un ambiente controlado donde una vez terminen de hacer sus cambios puedan hacer sus PR

La idea es seleccionar una y hacer una prueba de concepto a ver que tal funciona

## Ventajas

Mas facilidad al contribuir sin requerir un background tecnico avanzado

## Desventajas

Estas plataformas tienen un costo en horas, por ejemplo en el caso de github codespaces tiene una capa gratuita de hasta 60 hrs al mes, y gitpod hasta 50hrs

**Comment by andresperezcera** [comment]
Yo acabo de dedicar un rato a trabajar en codespaces. Alli se resuelve todo simplemente ejecutando un codespace y ejecutando `pip install -r requirements.txt`  + `lektor server`. Es posible crear codespaces de una organización, pero cada persona tiene acceso a esas 60 horas de uso personal, que serían mas que suficientes para las contribuciones de personas no tecnicas.

## Instrucciones simples en proceso simple
Pensaba en este orden de ideas actualizar el documento contributing.md para incluir 2 cosas: 
1. En contributing.md no se menciona con claridad como contribuir con un articulo. Se puede mencionar una contribución de ejemplo señalando el Issue Creado, el fork, branch, pull request y finalmente su publicación.
2. Crear un articulo especificamente tratando el tema de contribuir usando codespaces y dirigir a el desde contributing. Para esto se necesitaría definir si se creará una configuración de prebuild o si basta con mencionar la necesidad de ejecutar esos 2 comandos mencionados.

## CMS (Content management system) como [Wagtail](https://wagtail.org/)
El problema de contribuir sin barreras tecnicas solo se solventaría al 100% migrando bien sea la pagina completa o el blog a un CMS como wagtail (lo menciono por ser basado en django y ofrecer muchas funciones necesarias de manera predeterminada). Las desventajas que veo de esto son:

- La barrera tecnica para poder contribuir a cambios de estilo y función en la pagina se incrementa significativamente.
- Requiere de la conformación de roles de redacción, edición y publicación (lo que no es necesariamente malo).
- El indudable trabajo de desarrollo.
- Requiere de un servidor. (En este item puedo ofrecer un [Nanode 1GB](https://www.linode.com/pricing/#compute-shared))
