### ISSUE TITLE
En la versión en inglés solo deberían aparecer articulos traducidos

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/website#389]
# Solicitud de mejora en sitio web PyBAQ

En la versión en inglés solo deberían aparecer artículos que cuenten con traducción al inglés https://pybaq.co/en/blog/

## Ventajas

Mejorar la legibilidad de los lectores angloparlantes

## Desventajas

Se está mostrando información en español para un público internacional que **habla inglés**.

**Comment by Scot3004** [comment]
La forma mas facil de hacer esto, es crear en cada carpeta de pagina el archivo 
`contents+en.lr`

Con el siguiente contenido
```text
_discoverable: no
```

![image](https://user-images.githubusercontent.com/1175402/233372240-4f0c3909-ce37-4e71-a4b7-68811dcb7b04.png)

Pero identifique los siguientes problemas

- No hay blog posts en ingles
- En nosotros, los perfiles de cada uno de nosotros tiene la traducción automatica, pero la versión en ingles no tiene las contribuciones (campo markdown) en ingles, y los enlaces a los blog posts escritos solo mostraria aquellos posts traducidos (lo cual me hace mucho sentido)
- En la página de eventos los titulos no cuentan con traducciones (de hecho este numeral no se va a poder corregir, hasta que se haga un refactor de los eventos, por que en la API vienen en español) y estamos asociando el flowblock con el json usando el nombre como identificador de relación, esto hay que tenerlo en cuenta para cuando queramos tener las páginas de eventos individuales

**Comment by pyjavo** [comment]
Buen punto. 

Pienso en 2 escenarios:

1. Los eventos creo que deberían quedarse en español para no confundir al público angloparlante, ya que podrían pensar que la charlas y el contenido generado fue en inglés (cuando claramente fue en español).
Lo que me pone a pensar es si ese contenido duplicado genera alguna penalidad en el SEO 🤔
2. Traducirlos en inglés pero se debe dejar saber que la charla y el contenido generado fue en español. Tal vez con algún corchete luego del título. Ejemplo:
    - Lektor for dummies [spanish]
