### ISSUE TITLE
Mejorar Articulo "Contribuir en Modo Facil

### ISSUE THREAD

**Issue by andoresuperesu** [PyBAQ/website#391]
# Solicitud de mejora en sitio web PyBAQ

El articulo en mención tiene dos deficiencias resaltadas por miembros del proyecto:

- [ ] @Scot3004: Vincular articulo https://pybaq.co/blog/contribuir-blog-python-barranquilla/
- [ ] @pyjavo: Mejorar legibilidad en general.  No se entiende a que exactamente se refiere con "contribuir en modo fácil".
- [ ] @andresperezcera Traducir al inglés.

## Ventajas

Estaria en linea con el objetivo deseado en la discusión del issue #388 

## Desventajas

Ninguna.

**Comment by pyjavo** [comment]
Mejor especificar en que va a ser la contrubión. Dejo acá unos ejemplos:

**Título:** Contribuir a...
1. La pagina web
2. con un artículo
3. Con un artículo en la página web
4. a la página sin instalar lektor

... usando codespaces.

También se me ocurre que sería
 bueno agregar un enlace hacia github donde expliquen ¿qué es un codespace?

**Comment by andresperezcera** [comment]
La contribución puede ser código inclusive. La idea es solo señalar que se puede sin mayor lío usando codespaces y apuntar al otro artículo de como crear un artículo usando el administrador.

**Comment by pyjavo** [comment]
Vale, listo

**Comment by Scot3004** [comment]
"Cómo contribuir a la página web usando codespaces" esta guapo y conciso

**Comment by pyjavo** [comment]
Hola ¿cómo vas?
¿Necesitas ayuda con algo?

**Comment by andoresuperesu** [comment]
No
