### ISSUE TITLE
Traducir y actualizar el blog post Cómo contribuir en el blog de Python Barranquilla

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/website#393]
# Solicitud de mejora en sitio web PyBAQ

Traducir el blog post Cómo contribuir en el blog de Python Barranquilla
Ademas realizar las respectivas actualizaciones, dado que este post fue escrito en 2017 y han habido algunos cambios, que seria bueno resaltar en este blog post, por ejemplo la nueva guia de github codespaces

## Ventajas

Tener un blog post en ingles
Tener nuestra guia de contribución en ingles
Mostrar como se contribuye al dia de hoy, si bien la información en este blog post aún es vigente, hay que enlazar este articulo con el nuevo, y eso se lograria revisandolo y actualizandolo

## Desventajas

La fecha de publicación es un solo campo, pub_date y con este post caigo en cuenta que seria muy buena idea tener la fecha en la que el post se creo y una fecha con la ultima modificación, ya que como el post es de 2017 no se la forma correcta de actualizarlo si solo tenemos un campo de fecha, las alternativas que se me ocurren son:
- Editarlo, cambiar la fecha de creación, redirigir la url del viejo articulo al nuevo, colocar un comentario que este post fue creado originalmente en 2017, y publicarlo en redes sociales
- Editarlo sin cambiar la fecha de creación, y colocar un bloque donde se expliquen los cambios, pero en este caso no se que fecha de creación deberia tener la tradución
- Crear uno nuevo, mantener el viejo y enlazarlos

**Comment by pyjavo** [comment]
@Scot3004 lo que se suele hacer es dejar la fecha de creación tal como está y si hay actualizaciones, se escribe la fecha dentro del articulo (como parte del contenido). En realpython he visto varios artículos así. Ejemplo:

1. Mira que en el tercer parrafo dice **updates** https://realpython.com/kickstarting-flask-on-ubuntu-setup-and-deployment/ 
    - 10/28/2014: Added info on how to add a new user on Ubuntu
    - 04/16/2015: Updated nginx configuration

**Comment by pyjavo** [comment]
Se cierra porque según las analíticas, este tipo de artículos solo le interesa al publico de habla hispana
