### ISSUE TITLE
Pagina de contacto no deberia mostrar heading-title

### ISSUE THREAD

**Issue by Scot3004** [PyBAQ/website#411]
# Error en sitio web de python Barranquilla

## Comportamiento esperado

![Screenshot_20230617_200547](https://github.com/PyBAQ/website/assets/1175402/43d658de-3e88-4b03-ad44-961e1fc90b2b)

## Comportamiento actual

La página de contacto esta mostrando el bloque heading-title

![Screenshot_20230617_200708](https://github.com/PyBAQ/website/assets/1175402/8b95c2eb-dd0f-4ab5-a295-39e1ddf22f4a)

## Pasos para reproducir el error

1. Abrir la página de contacto

**Comment by pyjavo** [comment]
En ese caso los artículos también tienen un error porque tienen doble h1. Por un lado el título "blog" y por otro lado el título del mismo artículo

**Comment by Scot3004** [comment]
Interesante, no habia pensado en eso, @ArdaTX vos que sos el experto en seo, cuantos h1 deberia tener una página?

**Comment by pyjavo** [comment]
@Scot3004 es 1 solo por página
https://ahrefs.com/blog/es/etiqueta-h1/#usa-un-h1-por-pagina

**Comment by Scot3004** [comment]
si puede ser mas de 1 si se crea un section para el articulo 🙂
por ejemplo cambiando div class="blog-post" a section="blog-post"
