### ISSUE TITLE
Página de cada artículo no debería tener heading-title

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/website#413]
# Error en sitio web de python Barranquilla

## Comportamiento esperado

Debería haber solo un H1 por página. 
https://ahrefs.com/blog/es/etiqueta-h1/#usa-un-h1-por-pagina

## Comportamiento actual

Cada artículo del blog tiene dos H1.

Ejemplo: https://pybaq.co/blog/8-anos-en-retrospectiva-python-barranquilla/ tiene dos etiquetas H1:

```
- <h1>Blog</h1>
- <h1 class="ctitle">8 años en retrospectiva: Python Barranquilla</h1>
```

**Comment by Scot3004** [comment]
si puede ser mas de 1 si se crea un section para el articulo slightly_smiling_face
por ejemplo cambiando div class="blog-post" a section="blog-post"

En particular me gusta como se ve en los articulos esto, ademas da la idea de jerarquia si se mantiene, ya que el indice de blog lo muestra

**Comment by pyjavo** [comment]
Si hay más de 1, la jerarquía de los títulos se vería desordenada
![3-h1-tags-SPA](https://github.com/PyBAQ/website/assets/3085051/89d964af-7cc3-494c-a38b-93d9cbcc8511)

**Comment by Scot3004** [comment]
Una posibilidad es bajar los titulos del articulo a h2 :)
Asi se ve actualmente
![image](https://github.com/PyBAQ/website/assets/1175402/02625204-772c-4fe9-8a0b-a307471de647)

**Comment by pyjavo** [comment]
mmmmm 🤔

Veo que hay opiniones divididas https://support.google.com/webmasters/thread/15267057/having-multiple-h1-tags-hurt-seo?hl=en

¿Qué opina @ArdaTX ?

**Comment by Scot3004** [comment]
Asi se veria despues del cambio
![image](https://github.com/PyBAQ/website/assets/1175402/bfb97a57-b46b-4ba3-a76c-3e7dce6c8b6e)

**Comment by Scot3004** [comment]
En nosotros miembros lo atacamos usando un h2 para el nombre de cada uno, podriamos hacer lo mismo aca :)

**Comment by ArdaTX** [comment]
Un H1 está bien por página como dice scott  el resto se puede trabajar con
H2 y H3

**Comment by Scot3004** [comment]
De hecho para agravar la situación de todos modos deberíamos tener un section para el markdown, por qué tenemos algunos artículos que hacen uso del h1 para marcar títulos


En markdown el # solito

**Comment by pyjavo** [comment]
¿Pero entonces tendremos 10 o 15 artículos con el mismo titulo h1 de "Blog"?

Mi opinion es que se mantenga el H1 para los titulos de cada artículo y se elimine el título "Blog" de cada artículo

**Comment by ArdaTX** [comment]
De echo hay bastantes artículos sin H1 con H1 duplicados o sin implementar

**Comment by ArdaTX** [comment]
Es correcto Javier esa seria la solución
