### ISSUE TITLE
Deberia incluirse el plugin lektor-markdown-header-anchors

### ISSUE THREAD

**Issue by andresperezcera** [PyBAQ/website#421]
# Solicitud de mejora en sitio web PyBAQ

Deberia incluirse el plugin [lektor-markdown-header-anchors](https://github.com/lektor/lektor-markdown-header-anchors) en el repositorio.

## Ventajas

Genera anchors a cada titulo de los articulos y da acceso a crear tablas de contenido. También permitiría hacer links especificos a secciones de otros articulos; lo que daria contexto a la relación entre articulos como "Contribuir en Modo Facil" y "Cómo contribuir en el blog de Python Barranquilla"

## Desventajas

No encuentro desventajas hasta el momento. El plugin es mantenido por los mantainers de Lektor y el uso es muy específico. Puede ser útil a otros modelos de la pagina.

**Comment by andresperezcera** [comment]
@pyjavo @Scot3004 Esto no crea tablas, sino que crea un id en los titulos de markdown con el slug del titulo.

HTML generado ahora:
![image](https://github.com/PyBAQ/website/assets/11465755/9118ac2c-2585-4b37-98e8-1dd77e6352b2)


HTML generado con el plugin:
![image](https://github.com/PyBAQ/website/assets/11465755/aa12dbf1-a497-472a-b38d-b73d65a41abf)

Sin embargo, podria en la plantilla crearse una tabla de contenido si se quisiera porque el plugin tambien [expone la propiedad](https://github.com/lektor/lektor-markdown-header-anchors) `.toc`:

![image](https://github.com/PyBAQ/website/assets/11465755/e0c87d24-e04a-4608-b9d6-1ac6313122fa)

Esta propiedad permitiría incluir una tabla de contenido. Pero el objetivo es que permita citar con mayor precisión otros articulos en la pagina. Esta necesidad la descubrí al intentar citar una parte de un articulo del blog.

**Comment by Scot3004** [comment]
Y por eso mencioné los enlaces estilo GitHub o una tabla de contenido, sino nadie va a saber de estos enlaces

**Comment by andresperezcera** [comment]
El PR se trata solo de agregar el plugin, no tiene ningún otro alcance más allá de habilitar el atributo id con el correspondiente slug.

**Comment by pyjavo** [comment]
@andresperezcera ¡Super! Entonces por cada artículo que queramos, colocamos la tabla o agregamos eso un archivo "base" y que todos los artículos tengan esa tabla

@Scot3004 podriamos agregar la tabla de contenido algunos artículos para probar. 
Aún no entiendo a que te refieres con enlaces estilo github 😅

**Comment by Scot3004** [comment]
![image](https://github.com/PyBAQ/website/assets/1175402/52c4fad1-2183-445d-a9a5-615ef950d37b)
me refiero a cuando colocas el mouse sobre un titulo te aparece un botón para copiar el enlace

**Comment by andresperezcera** [comment]
@pyjavo Yo sería partidario de agregar un campo booleano al modelo que se llame TOC o TDC y que cada quien marque si lo quiere agregar o no. También creería que este PR es super sencillo y mejor si se mantiene así. Puedo crear otro issue citando esta conversación en el que sea mas explicito.
En este issue:
- Activar el plugin

Nuevo Issue:
- Modificar modelo de BlogPost agregando nuevo campo booleano de TDC (Tabla de Contenido).
- Agregar una TDC a la plantilla usando el ejemplo mostrado en este [link](https://github.com/lektor/lektor-markdown-header-anchors#in-templates)
- Crear maqueta de articulo con TDC.
- Modificar plantilla de articulo de blog para incluir TDC opcional.
- Crear CSS de TDC para artículos del Blog

La condición que tu mencionas @Scot3004 no es parte de este plugin, quizá podría darse con JavaScript. Pero si se menciona en el [PR #12](https://github.com/lektor/lektor-markdown-header-anchors/pull/12), para lograrla tendria que agregarse el plugin como un paquete ¿Quieres que lo intente?

**Comment by pyjavo** [comment]
Ok. De acuerdo 👍  
Vayamos paso a paso (issue por issue)

**Comment by andresperezcera** [comment]
@pyjavo @Scot3004 La pregunta es:
Aceptan el PR como está o quieren que se intente agregar como paquete el plugin con el [PR#13](https://github.com/lektor/lektor-markdown-header-anchors/pull/13) de ese repo que incluye links del tipo github? Es para saber si hay alguna tarea que agregar al #422.

Si se acepta como está, no se podrían agregar links tipo GitHub, sino que sería un PR aparte.

En cualquier caso tendria que haber otro issue que se trate de la implementación de TDC usando la propiedad `.toc`.

**Comment by Scot3004** [comment]
Así está bien
