### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/website#518]
# Solicitud de mejora en sitio web PyBAQ

Se observa una alerta en el github action "desplegar" por parte de Github.

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Vea por ejemplo https://github.com/PyBAQ/website/actions/runs/9603910483

## Ventajas

Progresivamente ir actualizando la paqueteria del proyecto

## Desventajas

¿Quién ayuda con esto?

**Comment by Scot3004** [comment]
Yo me encargo, lo que hay que hacer es similar a lo que se hizo para el action de actualizar eventos
