### ISSUE TITLE
Listado de charlas por perfil

### ISSUE THREAD

**Issue by pyjavo** [PyBAQ/website#556]
# Solicitud de mejora en sitio web PyBAQ

Parece que la lógica lista los eventos por perfil, pero debería listar las charlas específicas por persona.

Por ejemplo, en https://pybaq.co/nosotros/sergio-orozco/ vemos que no se sabe cual fue su última charla, ya que se lista el nombre del evento

## Ventajas

Ver las charlas realizadas por perfil

**Comment by pyjavo** [comment]
@Scot3004 ¿Qué tal si se crea un JSON o YAML con los listados de perfiles por charla y a partir de ahi se genera la información?

**Comment by Scot3004** [comment]
Entonces más bien lo que habría que hacer es mostrar el nombre de la charla y cual fue el evento, creo que deberíamos analizar cuales son los casos donde queremos ver esto porque está necesidad es más visible en eventos con múltiples charlas, pero en aquellos con una única charla, tanto el evento como la charla tienen el mismo nombre

**Comment by pyjavo** [comment]
Mmmmm ¿por qué debemos mostrar el nombre del evento? @Scot3004 
Si solo vamos a mostrar un listado con las charlas de la persona. En cada perfil, creo que mostrar el nombre del evento es irrelevante porque tiene un propósito más de mostrar habilidades (como un portafolio). Aunque si creo que necesitamos el enlace del evento así como está ahora

**Comment by Scot3004** [comment]
Ah bueno, más simple, me gusta
